import json
import re
import os

new_books = [
    # Computer Science (cs21-cs30)
    {"id": 'cs21', "title": 'The Art of Computer Programming', "author": 'Donald Knuth', "branch": 'computer-science', "subject": 'DSA', "rating": 4.9, "availableCopies": 2, "rackNumber": 'CS-601', "coverImage": 'https://images.unsplash.com/photo-1550439062-609e1531270e?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Faculty Recommended'], "year": 1968, "desc": 'A comprehensive monograph written by computer scientist Donald Knuth.'},
    {"id": 'cs22', "title": 'Computer Systems: A Programmer\\'s Perspective', "author": 'Randal E. Bryant', "branch": 'computer-science', "subject": 'Software Engineering', "rating": 4.8, "availableCopies": 5, "rackNumber": 'CS-602', "coverImage": 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 2002, "desc": 'Explains the underlying elements common among all computer systems.'},
    {"id": 'cs23', "title": 'Domain-Driven Design', "author": 'Eric Evans', "branch": 'computer-science', "subject": 'Software Engineering', "rating": 4.7, "availableCopies": 3, "rackNumber": 'CS-603', "coverImage": 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 2003, "desc": 'Tackling Complexity in the Heart of Software.'},
    {"id": 'cs24', "title": 'Site Reliability Engineering', "author": 'Niall Richard Murphy', "branch": 'computer-science', "subject": 'Networking', "rating": 4.6, "availableCopies": 4, "rackNumber": 'CS-604', "coverImage": 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 2016, "desc": 'How Google Runs Production Systems.'},
    {"id": 'cs25', "title": 'Code: The Hidden Language', "author": 'Charles Petzold', "branch": 'computer-science', "subject": 'Operating Systems', "rating": 4.8, "availableCopies": 6, "rackNumber": 'CS-605', "coverImage": 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1999, "desc": 'Understanding hardware and software.'},
    {"id": 'cs26', "title": 'Introduction to the Theory of Computation', "author": 'Michael Sipser', "branch": 'computer-science', "subject": 'DSA', "rating": 4.7, "availableCopies": 2, "rackNumber": 'CS-606', "coverImage": 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 1996, "desc": 'A standard textbook in theoretical computer science.'},
    {"id": 'cs27', "title": 'Effective Java', "author": 'Joshua Bloch', "branch": 'computer-science', "subject": 'Software Engineering', "rating": 4.9, "availableCopies": 10, "rackNumber": 'CS-607', "coverImage": 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Most Borrowed'], "year": 2001, "desc": 'Best practices for the Java programming language.'},
    {"id": 'cs28', "title": 'Patterns of Enterprise Application Architecture', "author": 'Martin Fowler', "branch": 'computer-science', "subject": 'Software Engineering', "rating": 4.6, "availableCopies": 1, "rackNumber": 'CS-608', "coverImage": 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2002, "desc": 'A guide to enterprise architecture.'},
    {"id": 'cs29', "title": 'The C Programming Language', "author": 'Brian W. Kernighan', "branch": 'computer-science', "subject": 'Software Engineering', "rating": 4.8, "availableCopies": 3, "rackNumber": 'CS-609', "coverImage": 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Faculty Recommended'], "year": 1978, "desc": 'The definitive reference for C.'},
    {"id": 'cs30', "title": 'The Phoenix Project', "author": 'Gene Kim', "branch": 'computer-science', "subject": 'Software Engineering', "rating": 4.7, "availableCopies": 8, "rackNumber": 'CS-610', "coverImage": 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 2013, "desc": 'A novel about IT, DevOps, and helping your business win.'},

    # Mechanical Engineering (me11-me20)
    {"id": 'me11', "title": 'Machine Elements in Mechanical Design', "author": 'Robert L. Mott', "branch": 'mechanical', "subject": 'Machine Design', "rating": 4.5, "availableCopies": 4, "rackNumber": 'ME-401', "coverImage": 'https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2003, "desc": 'Concepts and procedures for designing machine elements.'},
    {"id": 'me12', "title": 'Marks\\' Standard Handbook for Mechanical Engineers', "author": 'Eugene A. Avallone', "branch": 'mechanical', "subject": 'Machine Design', "rating": 4.8, "availableCopies": 2, "rackNumber": 'ME-402', "coverImage": 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Faculty Recommended'], "year": 1916, "desc": 'Comprehensive reference for mechanical engineers.'},
    {"id": 'me13', "title": 'Vibration of Mechanical Systems', "author": 'Alok Sinha', "branch": 'mechanical', "subject": 'Machine Design', "rating": 4.4, "availableCopies": 5, "rackNumber": 'ME-403', "coverImage": 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2010, "desc": 'An introduction to mechanical vibrations.'},
    {"id": 'me14', "title": 'Gas Dynamics', "author": 'Ethirajan Rathakrishnan', "branch": 'mechanical', "subject": 'Fluid Mechanics', "rating": 4.3, "availableCopies": 3, "rackNumber": 'ME-404', "coverImage": 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2005, "desc": 'A comprehensive approach to gas dynamics.'},
    {"id": 'me15', "title": 'Introduction to Flight', "author": 'John D. Anderson', "branch": 'mechanical', "subject": 'Fluid Mechanics', "rating": 4.7, "availableCopies": 6, "rackNumber": 'ME-405', "coverImage": 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 1978, "desc": 'An engaging introduction to aerospace engineering.'},
    {"id": 'me16', "title": 'Roark\\'s Formulas for Stress and Strain', "author": 'Warren C. Young', "branch": 'mechanical', "subject": 'Machine Design', "rating": 4.8, "availableCopies": 2, "rackNumber": 'ME-406', "coverImage": 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 1938, "desc": 'The definitive resource for designers and engineers.'},
    {"id": 'me17', "title": 'Principles of Heat Transfer', "author": 'Frank Kreith', "branch": 'mechanical', "subject": 'Heat Transfer', "rating": 4.5, "availableCopies": 4, "rackNumber": 'ME-407', "coverImage": 'https://images.unsplash.com/photo-1590422749909-0d17d591bd2c?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1958, "desc": 'A textbook covering heat transfer fundamentals.'},
    {"id": 'me18', "title": 'Mechatronics', "author": 'William Bolton', "branch": 'mechanical', "subject": 'Robotics', "rating": 4.6, "availableCopies": 3, "rackNumber": 'ME-408', "coverImage": 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 1995, "desc": 'Electronic control systems in mechanical and electrical engineering.'},
    {"id": 'me19', "title": 'Applied Thermodynamics', "author": 'Onkar Singh', "branch": 'mechanical', "subject": 'Thermodynamics', "rating": 4.2, "availableCopies": 5, "rackNumber": 'ME-409', "coverImage": 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2003, "desc": 'Applications of thermodynamics in engineering.'},
    {"id": 'me20', "title": 'Manufacturing Engineering and Technology', "author": 'Serope Kalpakjian', "branch": 'mechanical', "subject": 'Machine Design', "rating": 4.7, "availableCopies": 7, "rackNumber": 'ME-410', "coverImage": 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 1989, "desc": 'An indispensable text for manufacturing engineers.'},

    # Civil Engineering (ce11-ce20)
    {"id": 'ce11', "title": 'Design of Steel Structures', "author": 'S.K. Duggal', "branch": 'civil', "subject": 'Structural Analysis', "rating": 4.4, "availableCopies": 4, "rackNumber": 'CE-201', "coverImage": 'https://images.unsplash.com/photo-1589828497678-7711d9a26368?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2000, "desc": 'Comprehensive guide on steel design.'},
    {"id": 'ce12', "title": 'Geotechnical Engineering', "author": 'C. Venkatramaiah', "branch": 'civil', "subject": 'Soil Mechanics', "rating": 4.3, "availableCopies": 2, "rackNumber": 'CE-202', "coverImage": 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1995, "desc": 'Principles and practices of soils engineering.'},
    {"id": 'ce13', "title": 'Water Resources Engineering', "author": 'Larry W. Mays', "branch": 'civil', "subject": 'Environmental', "rating": 4.6, "availableCopies": 3, "rackNumber": 'CE-203', "coverImage": 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 2001, "desc": 'Modern methods for water resources management.'},
    {"id": 'ce14', "title": 'Advanced Structural Analysis', "author": 'Devdas Menon', "branch": 'civil', "subject": 'Structural Analysis', "rating": 4.7, "availableCopies": 1, "rackNumber": 'CE-204', "coverImage": 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2009, "desc": 'Advanced concepts in structural engineering.'},
    {"id": 'ce15', "title": 'Building Construction', "author": 'B.C. Punmia', "branch": 'civil', "subject": 'Environmental', "rating": 4.5, "availableCopies": 6, "rackNumber": 'CE-205', "coverImage": 'https://images.unsplash.com/photo-1541888081622-19e42108ec73?auto=format&fit=crop&q=80&w=400', "tags": ['Most Borrowed'], "year": 1984, "desc": 'Standard reference for building materials and methods.'},
    {"id": 'ce16', "title": 'Foundation Engineering', "author": 'P.C. Varghese', "branch": 'civil', "subject": 'Soil Mechanics', "rating": 4.2, "availableCopies": 3, "rackNumber": 'CE-206', "coverImage": 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2005, "desc": 'Detailed design approaches for foundations.'},
    {"id": 'ce17', "title": 'Traffic Engineering and Design', "author": 'R.J. Salter', "branch": 'civil', "subject": 'Transportation', "rating": 4.3, "availableCopies": 2, "rackNumber": 'CE-207', "coverImage": 'https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1989, "desc": 'Principles of modern traffic engineering.'},
    {"id": 'ce18', "title": 'Irrigation Engineering', "author": 'N.N. Basak', "branch": 'civil', "subject": 'Environmental', "rating": 4.1, "availableCopies": 5, "rackNumber": 'CE-208', "coverImage": 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1999, "desc": 'Covers major topics in irrigation and hydraulic structures.'},
    {"id": 'ce19', "title": 'Theory of Structures', "author": 'S. Ramamrutham', "branch": 'civil', "subject": 'Structural Analysis', "rating": 4.5, "availableCopies": 4, "rackNumber": 'CE-209', "coverImage": 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 1993, "desc": 'A widely used book for strength of materials and structures.'},
    {"id": 'ce20', "title": 'Airport Engineering', "author": 'Norman J. Ashford', "branch": 'civil', "subject": 'Transportation', "rating": 4.4, "availableCopies": 1, "rackNumber": 'CE-210', "coverImage": 'https://images.unsplash.com/photo-1465447142348-e9952c393450?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1992, "desc": 'Planning, design, and development of 21st-century airports.'},

    # Electrical Engineering (ee11-ee20)
    {"id": 'ee11', "title": 'The Art of Electronics', "author": 'Paul Horowitz', "branch": 'electrical', "subject": 'Digital Electronics', "rating": 4.9, "availableCopies": 5, "rackNumber": 'EE-201', "coverImage": 'https://images.unsplash.com/photo-1517077304055-6e89aadf09f0?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Bestseller'], "year": 1980, "desc": 'A classic reference on electronic circuit design.'},
    {"id": 'ee12', "title": 'Electric Power Systems', "author": 'B.M. Weedy', "branch": 'electrical', "subject": 'Power Systems', "rating": 4.5, "availableCopies": 3, "rackNumber": 'EE-202', "coverImage": 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1967, "desc": 'A comprehensive overview of power systems.'},
    {"id": 'ee13', "title": 'Electromagnetic Field Theory Fundamentals', "author": 'Bhag Singh Guru', "branch": 'electrical', "subject": 'Power Systems', "rating": 4.4, "availableCopies": 2, "rackNumber": 'EE-203', "coverImage": 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 1998, "desc": 'Fundamentals of electromagnetics.'},
    {"id": 'ee14', "title": 'Introduction to Robotics', "author": 'John J. Craig', "branch": 'electrical', "subject": 'Control Systems', "rating": 4.7, "availableCopies": 4, "rackNumber": 'EE-204', "coverImage": 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 1986, "desc": 'Mechanics and control of robotics.'},
    {"id": 'ee15', "title": 'Communication Systems', "author": 'Simon Haykin', "branch": 'electrical', "subject": 'Signal Processing', "rating": 4.6, "availableCopies": 6, "rackNumber": 'EE-205', "coverImage": 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400', "tags": ['Most Borrowed'], "year": 2000, "desc": 'An introduction to analog and digital communications.'},
    {"id": 'ee16', "title": 'Power Electronics', "author": 'M.H. Rashid', "branch": 'electrical', "subject": 'Power Systems', "rating": 4.5, "availableCopies": 3, "rackNumber": 'EE-206', "coverImage": 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1988, "desc": 'Circuits, devices, and applications.'},
    {"id": 'ee17', "title": 'Digital Image Processing', "author": 'Rafael C. Gonzalez', "branch": 'electrical', "subject": 'Signal Processing', "rating": 4.8, "availableCopies": 2, "rackNumber": 'EE-207', "coverImage": 'https://images.unsplash.com/photo-1558346490-a72e53ae874e?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 1977, "desc": 'The leading textbook in its field for more than twenty years.'},
    {"id": 'ee18', "title": 'Semiconductor Physics and Devices', "author": 'Donald Neamen', "branch": 'electrical', "subject": 'Digital Electronics', "rating": 4.4, "availableCopies": 4, "rackNumber": 'EE-208', "coverImage": 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1992, "desc": 'Basic principles of semiconductor devices.'},
    {"id": 'ee19', "title": 'Automatic Control Systems', "author": 'Benjamin C. Kuo', "branch": 'electrical', "subject": 'Control Systems', "rating": 4.5, "availableCopies": 3, "rackNumber": 'EE-209', "coverImage": 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1962, "desc": 'A classic textbook on control engineering.'},
    {"id": 'ee20', "title": 'Renewable Energy Resources', "author": 'John Twidell', "branch": 'electrical', "subject": 'Power Systems', "rating": 4.6, "availableCopies": 7, "rackNumber": 'EE-210', "coverImage": 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=400', "tags": ['Trending', 'New Arrival'], "year": 1986, "desc": 'Comprehensive guide to renewable energy technologies.'},

    # Mathematics (ma11-ma20)
    {"id": 'ma11', "title": 'Principles of Mathematical Analysis', "author": 'Walter Rudin', "branch": 'mathematics', "subject": 'Calculus', "rating": 4.9, "availableCopies": 3, "rackNumber": 'MA-201', "coverImage": 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Faculty Recommended'], "year": 1953, "desc": 'Often called "Baby Rudin," a classic real analysis text.'},
    {"id": 'ma12', "title": 'Algebra', "author": 'Serge Lang', "branch": 'mathematics', "subject": 'Linear Algebra', "rating": 4.7, "availableCopies": 2, "rackNumber": 'MA-202', "coverImage": 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1965, "desc": 'A comprehensive and rigorous graduate-level algebra text.'},
    {"id": 'ma13', "title": 'Numerical Analysis', "author": 'Richard L. Burden', "branch": 'mathematics', "subject": 'Calculus', "rating": 4.5, "availableCopies": 5, "rackNumber": 'MA-203', "coverImage": 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1978, "desc": 'Introduction to numerical approximation techniques.'},
    {"id": 'ma14', "title": 'Graph Theory', "author": 'Reinhard Diestel', "branch": 'mathematics', "subject": 'Discrete Math', "rating": 4.8, "availableCopies": 4, "rackNumber": 'MA-204', "coverImage": 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 1997, "desc": 'A standard textbook on graph theory.'},
    {"id": 'ma15', "title": 'An Introduction to Probability Theory', "author": 'William Feller', "branch": 'mathematics', "subject": 'Probability', "rating": 4.9, "availableCopies": 2, "rackNumber": 'MA-205', "coverImage": 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1950, "desc": 'A landmark book on probability theory.'},
    {"id": 'ma16', "title": 'Real and Complex Analysis', "author": 'Walter Rudin', "branch": 'mathematics', "subject": 'Calculus', "rating": 4.8, "availableCopies": 3, "rackNumber": 'MA-206', "coverImage": 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1966, "desc": 'Often called "Papa Rudin."'},
    {"id": 'ma17', "title": 'Mathematical Statistics', "author": 'John E. Freund', "branch": 'mathematics', "subject": 'Probability', "rating": 4.4, "availableCopies": 6, "rackNumber": 'MA-207', "coverImage": 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1962, "desc": 'A comprehensive introduction to statistics.'},
    {"id": 'ma18', "title": 'Differential Geometry of Curves and Surfaces', "author": 'Manfredo P. do Carmo', "branch": 'mathematics', "subject": 'Calculus', "rating": 4.7, "availableCopies": 2, "rackNumber": 'MA-208', "coverImage": 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1976, "desc": 'A widely used introduction to differential geometry.'},
    {"id": 'ma19', "title": 'Introduction to Operations Research', "author": 'Frederick S. Hillier', "branch": 'mathematics', "subject": 'Discrete Math', "rating": 4.6, "availableCopies": 5, "rackNumber": 'MA-209', "coverImage": 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 1967, "desc": 'A comprehensive introduction to optimization models.'},
    {"id": 'ma20', "title": 'Advanced Calculus', "author": 'Patrick M. Fitzpatrick', "branch": 'mathematics', "subject": 'Calculus', "rating": 4.5, "availableCopies": 3, "rackNumber": 'MA-210', "coverImage": 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1996, "desc": 'A rigorous text on advanced calculus.'},

    # Science (sc11-sc20)
    {"id": 'sc11', "title": 'A Brief History of Time', "author": 'Stephen Hawking', "branch": 'science', "subject": 'Physics', "rating": 4.8, "availableCopies": 10, "rackNumber": 'SC-201', "coverImage": 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Trending'], "year": 1988, "desc": 'From the Big Bang to Black Holes.'},
    {"id": 'sc12', "title": 'The Selfish Gene', "author": 'Richard Dawkins', "branch": 'science', "subject": 'Biology', "rating": 4.7, "availableCopies": 8, "rackNumber": 'SC-202', "coverImage": 'https://images.unsplash.com/photo-1530213786676-415b0d4749cc?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1976, "desc": 'A popular science book on evolution.'},
    {"id": 'sc13', "title": 'Cosmos', "author": 'Carl Sagan', "branch": 'science', "subject": 'Physics', "rating": 4.9, "availableCopies": 5, "rackNumber": 'SC-203', "coverImage": 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Most Borrowed'], "year": 1980, "desc": 'The story of 15 billion years of cosmic evolution.'},
    {"id": 'sc14', "title": 'Genetics: Analysis and Principles', "author": 'Robert Brooker', "branch": 'science', "subject": 'Biology', "rating": 4.5, "availableCopies": 4, "rackNumber": 'SC-204', "coverImage": 'https://images.unsplash.com/photo-1530213786676-415b0d4749cc?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1999, "desc": 'A comprehensive textbook on genetics.'},
    {"id": 'sc15', "title": 'The Feynman Lectures on Physics', "author": 'Richard P. Feynman', "branch": 'science', "subject": 'Physics', "rating": 4.9, "availableCopies": 2, "rackNumber": 'SC-205', "coverImage": 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Faculty Recommended'], "year": 1964, "desc": 'A physics masterpiece.'},
    {"id": 'sc16', "title": 'Chemistry: The Central Science', "author": 'Theodore L. Brown', "branch": 'science', "subject": 'Chemistry', "rating": 4.6, "availableCopies": 6, "rackNumber": 'SC-206', "coverImage": 'https://images.unsplash.com/photo-1603126857599-f6e157825828?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 1977, "desc": 'A widely used chemistry textbook.'},
    {"id": 'sc17', "title": 'Silent Spring', "author": 'Rachel Carson', "branch": 'science', "subject": 'Biology', "rating": 4.8, "availableCopies": 4, "rackNumber": 'SC-207', "coverImage": 'https://images.unsplash.com/photo-1530213786676-415b0d4749cc?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1962, "desc": 'An environmental science classic.'},
    {"id": 'sc18', "title": 'Biochemistry', "author": 'Jeremy M. Berg', "branch": 'science', "subject": 'Chemistry', "rating": 4.7, "availableCopies": 3, "rackNumber": 'SC-208', "coverImage": 'https://images.unsplash.com/photo-1603126857599-f6e157825828?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 2002, "desc": 'A comprehensive look at biochemistry.'},
    {"id": 'sc19', "title": 'Astrophysics for People in a Hurry', "author": 'Neil deGrasse Tyson', "branch": 'science', "subject": 'Physics', "rating": 4.6, "availableCopies": 9, "rackNumber": 'SC-209', "coverImage": 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 2017, "desc": 'A quick and easy guide to the cosmos.'},
    {"id": 'sc20', "title": 'The Double Helix', "author": 'James D. Watson', "branch": 'science', "subject": 'Biology', "rating": 4.5, "availableCopies": 2, "rackNumber": 'SC-210', "coverImage": 'https://images.unsplash.com/photo-1530213786676-415b0d4749cc?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1968, "desc": 'A personal account of the discovery of the structure of DNA.'},

    # Fiction (fi11-fi20)
    {"id": 'fi11', "title": 'The Lord of the Rings', "author": 'J.R.R. Tolkien', "branch": 'fiction', "subject": 'Fantasy', "rating": 4.9, "availableCopies": 12, "rackNumber": 'FI-201', "coverImage": 'https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Bestseller'], "year": 1954, "desc": 'An epic high-fantasy novel.'},
    {"id": 'fi12', "title": 'Fahrenheit 451', "author": 'Ray Bradbury', "branch": 'fiction', "subject": 'Sci-Fi', "rating": 4.7, "availableCopies": 5, "rackNumber": 'FI-202', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1953, "desc": 'A dystopian novel about a future American society where books are outlawed.'},
    {"id": 'fi13', "title": 'Neuromancer', "author": 'William Gibson', "branch": 'fiction', "subject": 'Sci-Fi', "rating": 4.6, "availableCopies": 3, "rackNumber": 'FI-203', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1984, "desc": 'A seminal work in the cyberpunk genre.'},
    {"id": 'fi14', "title": 'The Picture of Dorian Gray', "author": 'Oscar Wilde', "branch": 'fiction', "subject": 'Classic Literature', "rating": 4.5, "availableCopies": 6, "rackNumber": 'FI-204', "coverImage": 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1890, "desc": 'A philosophical novel about vanity and morality.'},
    {"id": 'fi15', "title": 'Frankenstein', "author": 'Mary Shelley', "branch": 'fiction', "subject": 'Sci-Fi', "rating": 4.6, "availableCopies": 4, "rackNumber": 'FI-205', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1818, "desc": 'The story of a young scientist who creates a sapient creature.'},
    {"id": 'fi16', "title": 'The Martian', "author": 'Andy Weir', "branch": 'fiction', "subject": 'Sci-Fi', "rating": 4.8, "availableCopies": 7, "rackNumber": 'FI-206', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Trending'], "year": 2011, "desc": 'An American astronaut becomes stranded on Mars.'},
    {"id": 'fi17', "title": 'Crime and Punishment', "author": 'Fyodor Dostoevsky', "branch": 'fiction', "subject": 'Classic Literature', "rating": 4.7, "availableCopies": 3, "rackNumber": 'FI-207', "coverImage": 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1866, "desc": 'A profound psychological novel.'},
    {"id": 'fi18', "title": 'The Name of the Wind', "author": 'Patrick Rothfuss', "branch": 'fiction', "subject": 'Fantasy', "rating": 4.8, "availableCopies": 5, "rackNumber": 'FI-208', "coverImage": 'https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 2007, "desc": 'The heroic fantasy novel.'},
    {"id": 'fi19', "title": 'Foundation', "author": 'Isaac Asimov', "branch": 'fiction', "subject": 'Sci-Fi', "rating": 4.7, "availableCopies": 4, "rackNumber": 'FI-209', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1951, "desc": 'A classic science fiction series.'},
    {"id": 'fi20', "title": 'Wuthering Heights', "author": 'Emily Brontë', "branch": 'fiction', "subject": 'Classic Literature', "rating": 4.4, "availableCopies": 2, "rackNumber": 'FI-210', "coverImage": 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1847, "desc": 'A novel about intense and almost demonic love.'},

    # Philosophy (ph11-ph20)
    {"id": 'ph11', "title": 'The Social Contract', "author": 'Jean-Jacques Rousseau', "branch": 'philosophy', "subject": 'Ethics', "rating": 4.5, "availableCopies": 3, "rackNumber": 'PH-201', "coverImage": 'https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1762, "desc": 'Theories of political rights and society.'},
    {"id": 'ph12', "title": 'Utilitarianism', "author": 'John Stuart Mill', "branch": 'philosophy', "subject": 'Ethics', "rating": 4.6, "availableCopies": 4, "rackNumber": 'PH-202', "coverImage": 'https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1861, "desc": 'A classic exposition and defense of utilitarianism.'},
    {"id": 'ph13', "title": 'Phenomenology of Spirit', "author": 'G.W.F. Hegel', "branch": 'philosophy', "subject": 'Epistemology', "rating": 4.2, "availableCopies": 1, "rackNumber": 'PH-203', "coverImage": 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1807, "desc": 'One of Hegel\\'s most important works.'},
    {"id": 'ph14', "title": 'Tractatus Logico-Philosophicus', "author": 'Ludwig Wittgenstein', "branch": 'philosophy', "subject": 'Logic', "rating": 4.7, "availableCopies": 2, "rackNumber": 'PH-204', "coverImage": 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 1921, "desc": 'A major philosophical work of the twentieth century.'},
    {"id": 'ph15', "title": 'Leviathan', "author": 'Thomas Hobbes', "branch": 'philosophy', "subject": 'Ethics', "rating": 4.4, "availableCopies": 3, "rackNumber": 'PH-205', "coverImage": 'https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1651, "desc": 'A landmark work in political philosophy.'},
    {"id": 'ph16', "title": 'The Myth of Sisyphus', "author": 'Albert Camus', "branch": 'philosophy', "subject": 'Existentialism', "rating": 4.6, "availableCopies": 5, "rackNumber": 'PH-206', "coverImage": 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 1942, "desc": 'A philosophical essay on the absurd.'},
    {"id": 'ph17', "title": 'Fear and Trembling', "author": 'Søren Kierkegaard', "branch": 'philosophy', "subject": 'Existentialism', "rating": 4.5, "availableCopies": 2, "rackNumber": 'PH-207', "coverImage": 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 1843, "desc": 'A psychological and philosophical work.'},
    {"id": 'ph18', "title": 'Meditations on First Philosophy', "author": 'René Descartes', "branch": 'philosophy', "subject": 'Epistemology', "rating": 4.8, "availableCopies": 4, "rackNumber": 'PH-208', "coverImage": 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Faculty Recommended'], "year": 1641, "desc": 'A foundational text of modern Western philosophy.'},
    {"id": 'ph19', "title": 'The Art of War', "author": 'Sun Tzu', "branch": 'philosophy', "subject": 'Ethics', "rating": 4.7, "availableCopies": 8, "rackNumber": 'PH-209', "coverImage": 'https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Bestseller'], "year": -500, "desc": 'An ancient Chinese military treatise.'},
    {"id": 'ph20', "title": 'Zen and the Art of Motorcycle Maintenance', "author": 'Robert M. Pirsig', "branch": 'philosophy', "subject": 'Epistemology', "rating": 4.6, "availableCopies": 6, "rackNumber": 'PH-210', "coverImage": 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 1974, "desc": 'An inquiry into values.'},

    # Psychology (ps11-ps20)
    {"id": 'ps11', "title": 'The Interpretation of Dreams', "author": 'Sigmund Freud', "branch": 'psychology', "subject": 'Clinical Psychology', "rating": 4.4, "availableCopies": 3, "rackNumber": 'PS-201', "coverImage": 'https://images.unsplash.com/photo-1544716278-e513176f20b5?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1899, "desc": 'Introduces his theory of the unconscious with respect to dream interpretation.'},
    {"id": 'ps12', "title": 'The Man Who Mistook His Wife for a Hat', "author": 'Oliver Sacks', "branch": 'psychology', "subject": 'Neuropsychology', "rating": 4.6, "availableCopies": 5, "rackNumber": 'PS-202', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 1985, "desc": 'Clinical tales of neurological patients.'},
    {"id": 'ps13', "title": 'The Righteous Mind', "author": 'Jonathan Haidt', "branch": 'psychology', "subject": 'Behavioral Psychology', "rating": 4.7, "availableCopies": 4, "rackNumber": 'PS-203', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 2012, "desc": 'Why good people are divided by politics and religion.'},
    {"id": 'ps14', "title": 'Drive', "author": 'Daniel H. Pink', "branch": 'psychology', "subject": 'Behavioral Psychology', "rating": 4.5, "availableCopies": 6, "rackNumber": 'PS-204', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2009, "desc": 'The surprising truth about what motivates us.'},
    {"id": 'ps15', "title": 'Grit: The Power of Passion and Perseverance', "author": 'Angela Duckworth', "branch": 'psychology', "subject": 'Cognitive Science', "rating": 4.8, "availableCopies": 8, "rackNumber": 'PS-205', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Trending'], "year": 2016, "desc": 'Why passion and resilience are the secrets to success.'},
    {"id": 'ps16', "title": 'Social Intelligence', "author": 'Daniel Goleman', "branch": 'psychology', "subject": 'Behavioral Psychology', "rating": 4.4, "availableCopies": 2, "rackNumber": 'PS-206', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2006, "desc": 'The new science of human relationships.'},
    {"id": 'ps17', "title": 'Games People Play', "author": 'Eric Berne', "branch": 'psychology', "subject": 'Behavioral Psychology', "rating": 4.3, "availableCopies": 3, "rackNumber": 'PS-207', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1964, "desc": 'The psychology of human relationships.'},
    {"id": 'ps18', "title": 'Phantoms in the Brain', "author": 'V.S. Ramachandran', "branch": 'psychology', "subject": 'Neuropsychology', "rating": 4.7, "availableCopies": 4, "rackNumber": 'PS-208', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 1998, "desc": 'Probing the mysteries of the human mind.'},
    {"id": 'ps19', "title": 'The Body Keeps the Score', "author": 'Bessel van der Kolk', "branch": 'psychology', "subject": 'Clinical Psychology', "rating": 4.9, "availableCopies": 10, "rackNumber": 'PS-209', "coverImage": 'https://images.unsplash.com/photo-1544716278-e513176f20b5?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Most Borrowed'], "year": 2014, "desc": 'Brain, mind, and body in the healing of trauma.'},
    {"id": 'ps20', "title": 'Incognito: The Secret Lives of the Brain', "author": 'David Eagleman', "branch": 'psychology', "subject": 'Neuropsychology', "rating": 4.6, "availableCopies": 5, "rackNumber": 'PS-210', "coverImage": 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2011, "desc": 'Navigating the brain\\'s subconscious networks.'},

    # Business & Finance (bf11-bf20)
    {"id": 'bf11', "title": 'A Random Walk Down Wall Street', "author": 'Burton G. Malkiel', "branch": 'business-finance', "subject": 'Investing', "rating": 4.7, "availableCopies": 4, "rackNumber": 'BF-201', "coverImage": 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Faculty Recommended'], "year": 1973, "desc": 'The time-tested strategy for successful investing.'},
    {"id": 'bf12', "title": 'The E-Myth Revisited', "author": 'Michael E. Gerber', "branch": 'business-finance', "subject": 'Entrepreneurship', "rating": 4.6, "availableCopies": 5, "rackNumber": 'BF-202', "coverImage": 'https://images.unsplash.com/photo-1512314889357-e157c22f938d?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 1995, "desc": 'Why most small businesses don\\'t work and what to do about it.'},
    {"id": 'bf13', "title": 'Built to Last', "author": 'Jim Collins', "branch": 'business-finance', "subject": 'Corporate Strategy', "rating": 4.5, "availableCopies": 3, "rackNumber": 'BF-203', "coverImage": 'https://images.unsplash.com/photo-1553484771-047a44eee2cb?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1994, "desc": 'Successful habits of visionary companies.'},
    {"id": 'bf14', "title": 'Venture Deals', "author": 'Brad Feld', "branch": 'business-finance', "subject": 'Investing', "rating": 4.7, "availableCopies": 2, "rackNumber": 'BF-204', "coverImage": 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 2011, "desc": 'Be smarter than your lawyer and venture capitalist.'},
    {"id": 'bf15', "title": 'Start with Why', "author": 'Simon Sinek', "branch": 'business-finance', "subject": 'Leadership', "rating": 4.6, "availableCopies": 7, "rackNumber": 'BF-205', "coverImage": 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Trending'], "year": 2009, "desc": 'How great leaders inspire everyone to take action.'},
    {"id": 'bf16', "title": 'The Hard Thing About Hard Things', "author": 'Ben Horowitz', "branch": 'business-finance', "subject": 'Entrepreneurship', "rating": 4.8, "availableCopies": 4, "rackNumber": 'BF-206', "coverImage": 'https://images.unsplash.com/photo-1512314889357-e157c22f938d?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 2014, "desc": 'Building a business when there are no easy answers.'},
    {"id": 'bf17', "title": 'Freakonomics', "author": 'Steven D. Levitt', "branch": 'business-finance', "subject": 'Personal Finance', "rating": 4.5, "availableCopies": 6, "rackNumber": 'BF-207', "coverImage": 'https://images.unsplash.com/photo-1611016186353-9af58c69a533?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 2005, "desc": 'A rogue economist explores the hidden side of everything.'},
    {"id": 'bf18', "title": 'Blue Ocean Strategy', "author": 'W. Chan Kim', "branch": 'business-finance', "subject": 'Corporate Strategy', "rating": 4.6, "availableCopies": 3, "rackNumber": 'BF-208', "coverImage": 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 2005, "desc": 'How to create uncontested market space.'},
    {"id": 'bf19', "title": 'The Personal MBA', "author": 'Josh Kaufman', "branch": 'business-finance', "subject": 'Entrepreneurship', "rating": 4.7, "availableCopies": 5, "rackNumber": 'BF-209', "coverImage": 'https://images.unsplash.com/photo-1512314889357-e157c22f938d?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2010, "desc": 'Master the art of business.'},
    {"id": 'bf20', "title": 'Traction', "author": 'Gabriel Weinberg', "branch": 'business-finance', "subject": 'Marketing', "rating": 4.5, "availableCopies": 2, "rackNumber": 'BF-210', "coverImage": 'https://images.unsplash.com/photo-1553484771-047a44eee2cb?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 2014, "desc": 'How any startup can achieve explosive customer growth.'},

    # Self Development (sd11-sd20)
    {"id": 'sd11', "title": 'Outliers', "author": 'Malcolm Gladwell', "branch": 'self-development', "subject": 'Mindset', "rating": 4.7, "availableCopies": 8, "rackNumber": 'SD-201', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Trending'], "year": 2008, "desc": 'The story of success.'},
    {"id": 'sd12', "title": 'Dare to Lead', "author": 'Brené Brown', "branch": 'self-development', "subject": 'Communication', "rating": 4.8, "availableCopies": 6, "rackNumber": 'SD-202', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 2018, "desc": 'Brave work. Tough conversations. Whole hearts.'},
    {"id": 'sd13', "title": 'Daring Greatly', "author": 'Brené Brown', "branch": 'self-development', "subject": 'Mindset', "rating": 4.7, "availableCopies": 4, "rackNumber": 'SD-203', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2012, "desc": 'How the courage to be vulnerable transforms the way we live.'},
    {"id": 'sd14', "title": 'Make Your Bed', "author": 'William H. McRaven', "branch": 'self-development', "subject": 'Habit Building', "rating": 4.6, "availableCopies": 5, "rackNumber": 'SD-204', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Trending'], "year": 2017, "desc": 'Little things that can change your life... and maybe the world.'},
    {"id": 'sd15', "title": 'The 4-Hour Workweek', "author": 'Timothy Ferriss', "branch": 'self-development', "subject": 'Productivity', "rating": 4.5, "availableCopies": 3, "rackNumber": 'SD-205', "coverImage": 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller'], "year": 2007, "desc": 'Escape 9-5, live anywhere, and join the new rich.'},
    {"id": 'sd16', "title": 'The Power of Now', "author": 'Eckhart Tolle', "branch": 'self-development', "subject": 'Mindset', "rating": 4.7, "availableCopies": 7, "rackNumber": 'SD-206', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Classic', 'Bestseller'], "year": 1997, "desc": 'A guide to spiritual enlightenment.'},
    {"id": 'sd17', "title": 'You Are a Badass', "author": 'Jen Sincero', "branch": 'self-development', "subject": 'Mindset', "rating": 4.6, "availableCopies": 4, "rackNumber": 'SD-207', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": [], "year": 2013, "desc": 'How to stop doubting your greatness and start living an awesome life.'},
    {"id": 'sd18', "title": 'Can\\'t Hurt Me', "author": 'David Goggins', "branch": 'self-development', "subject": 'Mindset', "rating": 4.9, "availableCopies": 10, "rackNumber": 'SD-208', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Bestseller', 'Most Borrowed', 'Trending'], "year": 2018, "desc": 'Master your mind and defy the odds.'},
    {"id": 'sd19', "title": 'Crucial Conversations', "author": 'Kerry Patterson', "branch": 'self-development', "subject": 'Communication', "rating": 4.7, "availableCopies": 3, "rackNumber": 'SD-209', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Faculty Recommended'], "year": 2002, "desc": 'Tools for talking when stakes are high.'},
    {"id": 'sd20', "title": 'Mindfulness in Plain English', "author": 'Bhante Henepola Gunaratana', "branch": 'self-development', "subject": 'Mindset', "rating": 4.6, "availableCopies": 2, "rackNumber": 'SD-210', "coverImage": 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400', "tags": ['Classic'], "year": 1994, "desc": 'A practical guide to vipassana meditation.'}
]

with open('c:/Users/ADMIN/Desktop/shelfix/client/src/data/mockData.js', 'r', encoding='utf-8') as f:
    content = f.read()

# We need to find the ending bracket `];` of mockBooks and insert the new books before it.
# Convert books to a JS string format similar to what exists.

books_str_list = []
for b in new_books:
    tags_str = "[" + ", ".join([f"'{t}'" for t in b['tags']]) + "]"
    
    book_str = f"  {{ id: '{b['id']}', title: '{b['title'].replace(chr(39), chr(92)+chr(39))}', author: '{b['author']}', branch: '{b['branch']}', subject: '{b['subject']}', rating: {b['rating']}, availableCopies: {b['availableCopies']}, rackNumber: '{b['rackNumber']}', coverImage: '{b['coverImage']}', tags: {tags_str}, year: {b['year']}, desc: '{b['desc'].replace(chr(39), chr(92)+chr(39))}' }}"
    books_str_list.append(book_str)

insertion_str = ",\\n\\n" + ",\\n".join(books_str_list) + "\\n"

# Replace the last `];` with `, new_books];`
content = re.sub(r'\\n\];\\s*$', insertion_str + '];\\n', content)

with open('c:/Users/ADMIN/Desktop/shelfix/client/src/data/mockData.js', 'w', encoding='utf-8') as f:
    f.write(content)
print("Updated mockData.js with 100 new books.")
